# Dockerized Config And Eureka Server Compose
# Author: jackie-1685@163.com
# 

version: "3"
services:
  primary-config-server:
    image: mengluo668/config-server:0.0.1-SNAPSHOT
    restart: always
    ports:
      - 8888:8888
    volumes:
      - "/tmp/primary-config-server:/tmp"
      - "/var/configuration/config-server/primary:/config-server/config"
  primary-eureka-server:
    image: mengluo668/eureka-server:0.0.1-SNAPSHOT
    restart: always
    ports:
      - 8761:8761
    volumes:
      - "/tmp/primary-eureka-server:/tmp"
    environment:
      - DEFAULT_EUREKA_SERVER_SPRING_PROFILES_ACTIVE=primary
      - DEFAULT_EUREKA_SERVER_SPRING_CLOUD_CONFIG_ENABLED=true
      - DEFAULT_EUREKA_SERVER_SPRING_CLOUD_CONFIG_URI=http://35.185.131.60:8888/config-server
    depends_on:
      - primary-config-server
